<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE it-order [
    <!ELEMENT it-order (orders*)>
    <!ELEMENT orders (ID, name, product, amount, time, delivery-round)>
    
    <!ELEMENT ID (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT product (#PCDATA)>
    <!ELEMENT amount (#PCDATA)>
    <!ELEMENT time (#PCDATA)>
    <!ELEMENT delivery-round (#PCDATA)>

    <!ENTITY morning "รอบเช้า">
    <!ENTITY noon "รอบบ่าย">
    <!ENTITY night "รอบเย็น">
]>

<it-order>
    <orders>
        <ID>3001</ID>
        <name>นีร พงษ์ดี</name>
        <product>Kingston SSD 240GB</product>
        <amount>3 ชิ้น</amount>
        <time>08:15 น.</time>
        <delivery-round>&morning;</delivery-round>
    </orders>
    <orders>
        <ID>3002</ID>
        <name>แพรวา กุลจันทร์</name>
        <product>SanDisk Flash Drive 64GB</product>
        <amount>5 ชิ้น</amount>
        <time>13:45 น.</time>
        <delivery-round>&noon;</delivery-round>
    </orders>
    <orders>
        <ID>3003</ID>
        <name>ตฤณ ภูวดล</name>
        <product>Logitech Wireless Mouse M331</product>
        <amount>2 ชิ้น</amount>
        <time>19:10 น.</time>
        <delivery-round>&night;</delivery-round>
    </orders>
    <orders>
        <ID>3004</ID>
        <name>ขวัญ ศักดิ์ศรี</name>
        <product>Kingston SSD 240GB</product>
        <amount>1 ชิ้น</amount>
        <time>09:50 น.</time>
        <delivery-round>&morning;</delivery-round>
    </orders>
    <orders>
        <ID>3005</ID>
        <name>เอก ภักดี</name>
        <product>TOTOLINK Wi-Fi USB Adapter</product>
        <amount>1 ชิ้น</amount>
        <time>15:30 น.</time>
        <delivery-round>&noon;</delivery-round>
    </orders>
</it-order>
