<?xml version="1.0" encoding="UTF-8"?>  
<!DOCTYPE it-delivery [     
    <!ELEMENT it-delivery (deliverys*)>     
    <!ELEMENT deliverys (ID, name, product, company, deliveryround, status)>          

    <!ELEMENT ID (#PCDATA)>     
    <!ELEMENT name (#PCDATA)>     
    <!ELEMENT product (#PCDATA)>     
    <!ELEMENT company (#PCDATA)>     
    <!ELEMENT deliveryround (#PCDATA)>     
    <!ELEMENT status (#PCDATA)>      

    <!ENTITY not "ยังไม่จัดส่ง">     
    <!ENTITY shipping "กำลังจัดส่ง">     
    <!ENTITY completed "จัดส่งเรียบร้อย"> 
]>

<it-delivery>
    <deliverys>
        <ID>4001</ID>
        <name>นีร พงษ์ดี</name>
        <product>Kingston SSD 240GB</product>
        <company>ไปรษณีย์ไทย</company>
        <deliveryround>รอบเช้า</deliveryround>
        <status>&shipping;</status>
    </deliverys>
    <deliverys>
        <ID>4002</ID>
        <name>แพรวา กุลจันทร์</name>
        <product>SanDisk Flash Drive 64GB</product>
        <company>Flash Express</company>
        <deliveryround>รอบบ่าย</deliveryround>
        <status>&shipping;</status>
    </deliverys>
    <deliverys>
        <ID>4003</ID>
        <name>ตฤณ ภูวดล</name>
        <product>Logitech Wireless Mouse M331</product>
        <company>Shopee Express</company>
        <deliveryround>รอบเย็น</deliveryround>
        <status>&completed;</status>
    </deliverys>
    <deliverys>
        <ID>4004</ID>
        <name>ขวัญ ศักดิ์ศรี</name>
        <product>Kingston SSD 240GB</product>
        <company>ไปรษณีย์ไทย</company>
        <deliveryround>รอบเช้า</deliveryround>
        <status>&not;</status>
    </deliverys>
    <deliverys>
        <ID>4005</ID>
        <name>เอก ภักดี</name>
        <product>TOTOLINK Wi-Fi USB Adapter</product>
        <company>Flash Express</company>
        <deliveryround>รอบบ่าย</deliveryround>
        <status>&shipping;</status>
    </deliverys>
</it-delivery>
